name: 'Test workflow'

on:
  push:
    branches:
    - main

env:
  ENV_TEST: 'This test'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: bash
        shell: bash
        run: |
          echo $ENV_TEST
